### ISSUE TITLE
Cannot install on Macos

### ISSUE THREAD

**Issue by rockwotj** [googlefonts/noto-emoji#381] opened 2022-02-11 13:30 UTC
I run into this error trying to install these fonts on MacOS 12.2

<img width="855" alt="image" src="https://user-images.githubusercontent.com/8669100/153599986-9a0d6e33-9f1e-4923-befa-4fd0cae3a766.png">

**Comment by rsheeter** [comment] 2022-02-11 18:31
Closing as duplicate of #335

**Closed by rsheeter** 2022-02-11 18:31 UTC
