### ISSUE TITLE
Noto Emoji doesn't have a cmap 14 subtable

### ISSUE THREAD

**Issue by tursunova** [googlefonts/noto-emoji#472] opened 2024-06-14 13:54 UTC
Noto Emoji doesn't have a cmap 14 subtable. It would be useful to have cmap14 subtable for Variation Selector-15 in Noto Emoji font.

**Comment by drott** [comment] 2024-06-14 14:00
@anthrotype we talked about this before, IIRC. We're looking into improving variation selector support in Blink and VS15 cmap14 would be useful to discern Noto Emoji from Noto Emoji color.

**Comment by anthrotype** [comment] 2024-06-14 14:40
you mean the black and white Noto Emoji? https://fonts.google.com/noto/specimen/Noto+Emoji

because the Noto Color Emoji (both CBDT and COLRv1) definitely has one.

https://github.com/googlefonts/noto-emoji/blob/41e31b110b4eb929dffb410264694a06205b7ad7/Makefile#L218
https://github.com/googlefonts/noto-emoji/blob/41e31b110b4eb929dffb410264694a06205b7ad7/colrv1_postproc.py#L61

Yes, +1 to add a corresponding one for the b&w emoji font as well.

**Comment by drott** [comment] 2024-06-14 14:52
Closing, duplicate of https://github.com/googlefonts/emoji-bw/issues/30

**Closed by drott** 2024-06-14 14:52 UTC

**Comment by jbicha** [comment] 2024-06-16 15:14
@drott Is there any chance https://github.com/googlefonts/emoji-bw could be made public?

**Comment by drott** [comment] 2024-12-17 09:52
> [@drott](https://github.com/drott) Is there any chance https://github.com/googlefonts/emoji-bw could be made public?

@anthrotype is that something you could help with?
