### ISSUE TITLE
NotoColorEmoji.ttf not a valid font in Windows

### ISSUE THREAD

**Issue by vandasian** [googlefonts/noto-emoji#43] opened 2016-02-16 17:10 UTC
I've tried installing NotoColorEmoji.ttf in Windows 10 and it is not a valid font to install. From https://www.google.com/get/noto/ I've downloaded and extracted the font from both the individual font .zip and the complete Noto .zip file without success. An online font converter failed to convert it to a .ttf or an .otf for testing as well.
Windows 10 Build 10586.104

**Comment by jungshik** [comment] 2016-02-18 21:20
There are 3 formats for color fonts being standardized; 1. Google's proposal as used in Noto Color Emoji among other fonts 2. Microsoft's proposal  3. SVG-based format (mainly proposed by Mozilla and Adobe).  There's also a proprietary format used by Apple on Mac OS/iOS. 

Windows currently  supports one of them (quite naturally, it's what MS proposed) and does not support a format used in Noto Color Emoji, yet.

**Comment by vandasian** [comment] 2016-02-19 20:02
Can you comment on why there's no mention of this? No where does it say "this doesn't work on windows" :smiley:

**Comment by eosrei** [comment] 2016-02-25 01:42
@jungshik The standardization process completed 1/27/16 and the forth option was selected: https://www.w3.org/community/svgopentype/2016/01/27/opentype-spec-adopts-svg-in-opentype-proposal/

**Comment by behdad** [comment] 2016-02-25 02:38
> @jungshik The standardization process completed 1/27/16 and the forth option was selected: https://www.w3.org/community/svgopentype/2016/01/27/opentype-spec-adopts-svg-in-opentype-proposal/

No.  That post was created recently to point people away from the working group's draft.  In reality, the standardization process concluded in 2014, and all three of Microsoft's, Google's, and Adobe+Mozilla+W3C's proposals became part of OpenType and ISO version.  Indeed, you can see all of COLR+CPAL, SVG+CPAL, and CBLC+CBDT both on Microsoft's OpenType spec website as well as latest version of ISO OFF if you can get your hands on it.

https://www.microsoft.com/typography/otspec/otff.htm#otttables
http://standards.iso.org/ittf/PubliclyAvailableStandards/c066391_ISO_IEC_14496-22_2015.zip

**Comment by eosrei** [comment] 2016-02-25 02:42
Ah ha! Thanks for the correction and details. :)

**Comment by adrientetar** [comment] 2016-02-27 20:55
> , and all three of Microsoft's, Google's, and Adobe+Mozilla+W3C's proposals became part of OpenType and ISO version

Why three? Is there no single format to rule them all?

**Comment by behdad** [comment] 2016-02-28 02:55
> Why three? Is there no single format to rule them all?

The rule-all option is SVG, which is cumbersome to implement.  So the other two were accepted as much lighter ways to address existing needs: color bitmaps, and color layers.

**Comment by LinkofHyrule89** [comment] 2016-08-25 06:08
Is there any solution to using the front on Windows yet?

**Comment by eosrei** [comment] 2016-08-25 23:38
@LinkofHyrule89 Since the above conversation, I've made emoji fonts which work in Windows. https://github.com/eosrei/emojione-color-font#install-on-windows V1.3 and older shows color in Firefox only. V1.4+(when I release it) shows color on Windows 10 Edge V38.14393+ also. Sorry, not this graphic set because of #30. You can test your browser's color font support here: https://pixelambacht.nl/chromacheck/

**Comment by LinkofHyrule89** [comment] 2016-08-26 00:15
@eosrei after they fix #30 will you port noto-emoji to work on Windows? Also, the current version of Chrome on Windows doesn't natively support Emoji yet? Do you know if they are working on this problem?

**Comment by miguelsousa** [comment] 2016-08-26 05:35
> Is there any solution to using the front on Windows yet?

@LinkofHyrule89 the official font works as-is in Microsoft Edge, if you're running Windows 10 with the Anniversary Update.

<img width="1013" alt="notocoloremoji" src="https://cloud.githubusercontent.com/assets/2119742/17995143/0eada064-6b14-11e6-935d-c32a9486622e.png">

**Comment by eosrei** [comment] 2016-08-26 06:46
> will you port noto-emoji to work on Windows? 

I would have done it originally, but it wasn't an option. Now, the current CBDT/CBLC version works since Edge supports everything. I'd probably do it in SVGinOT anyway though if the SVGs were available.

> After installing your font it shows the black and white emoji and not the color ones.

Chrome supports COLR/CPAL and CBDT/CBLC on Windows. It doesn't support SVGinOT. My documentation specifically mention support in Firefox only, soon Edge. Chrome may add support in the future, but that's way outside of my purview. 

@RoelN bug report on https://pixelambacht.nl/chromacheck/ is this https://github.com/RoelN/ChromaCheck/issues/8 ?

**Comment by eosrei** [comment] 2016-08-26 07:07
Oh also, per @miguelsousa This issue can be closed.

**Comment by RoelN** [comment] 2016-08-26 07:30
Chrome on Windows doesn't support any color format yet — only the Android version supports CBDT.

The CBDT test in ChromaCheck has been fixed a couple of weeks ago, so it should report properly: https://github.com/RoelN/ChromaCheck/commit/c6889d62c907c32841a60c988c5c6601a0c09374

**Comment by LinkofHyrule89** [comment] 2016-08-26 08:02
Chrome does support the Microsoft color emoji format in the latest Chrome Dev because how else would it be displaying those? I did find this it says fixed.

https://bugs.chromium.org/p/chromium/issues/detail?id=333011

@miguelsousa but how did you install the font on Windows and run it in edge?

**Comment by RoelN** [comment] 2016-08-26 08:13
Ah yes, it is displaying color emoji in Window's own emoji font, Segoe UI. I checked in Dev and indeed COLR fonts work, but ChromaCheck says it doesn't. I'll look at this during lunch, will report back.

**Comment by LinkofHyrule89** [comment] 2016-08-26 08:16
@RoelN much appreciated is like to get to the bottom of all this. I'm hoping to switch the default font with the noto some day but at least we can know what font format Chrome Dev actually supports 😀

**Comment by RoelN** [comment] 2016-08-26 15:03
The COLR test of ChromaCheck in Chrome Dev 53 and 54 on Windows 10 failed because the font had a non-empty (no outline data) fallback glyph. I don't know why it fails on that, but I think it's a bug. I fixed this by simply using a non-empty glyph as the fallback glyph in ChromaCheck: https://github.com/RoelN/ChromaCheck/issues/31.

The CBDT font simply won't render so I suppose this is just not implemented in Chrome on Windows.

@eosrei Could the empty glyph thing be the case for the emoji in the COLR font? Or do you have singlecolor fallback emoji in there?

**Comment by eosrei** [comment] 2016-08-26 18:33
@RoelN Yes. *Segoe UI Emoji/Symbol* and my SVGinOT fonts (*EmojiOne Color* & *Twitter Color Emoji*) have fallback TrueType glyphs. *Noto Color Emoji* and *Apple Color Emoji* do not. SVGinOT was only supported in Firefox/Gecko when I made these fonts, so I [created TTF glyphs](https://github.com/eosrei/emojione-color-font/blob/5600c4106c4fad783dc260b95c844bc28206b5ab/Makefile#L98-L111) to make the fonts work everywhere. Also, fallback CFF/TT glyphs are needed for text vs emoji variation selectors VS15/VS16 ([which I haven't dealt with yet](https://github.com/eosrei/emojione-color-font/issues/22).)

**Comment by miguelsousa** [comment] 2016-08-26 19:30
> but how did you install the font on Windows and run it in edge?

@LinkofHyrule89 I didn't install the font. The webpage loads it via @font-face

**Comment by jungshik** [comment] 2016-08-26 20:13
Chrome on WIndows and Mac does not support CBDT-based color fonts (, yet). Chrome needs to bundle a subset of FreeType to support that. It has been talked about, but no movement so far.

**Comment by LinkofHyrule89** [comment] 2016-08-27 04:26
@miguelsousa is there a way to use CSS to use the @font-face to use the font on all web pages instead of Segoe?

**Comment by Milo359** [comment] 2016-10-06 01:46
When I try to open NotoColorEmoji.ttf with FontForge, it gives this error:

> No (usable) bitmap strikes in this TTF font

That may or may not help. :P

**Comment by bannmann** [comment] 2016-10-07 19:03
In case it helps anyone: Microsoft's [DirectWrite Programming Guide: Color fonts](https://msdn.microsoft.com/en-us/library/windows/desktop/mt765165(v=vs.85).aspx#what_kinds_of_color_fonts_does_windows_support_) says SVG-based color fonts are supported by DirectWrite/Direct2D as of Win10 Anniversary Edition. They claim to support only a subset of SVG, though.

**Comment by KrasnayaPloshchad** [comment] 2017-01-23 07:34
I think this font shouldn’t be limited by specific font technology.

**Comment by IganDeschain** [comment] 2017-08-10 22:12
Any word about this? I keep reading the the new anniversary update (1703) should work but I don't know how to start.

Installing via `right click -> install` gives an error.

**Comment by DeeDeeG** [comment] 2017-08-19 23:04
Try putting it in the `C:\Windows\Fonts` folder manually.

**Comment by IganDeschain** [comment] 2017-08-20 16:53
Pretty much _the same_ as installing it with right click.

Screenshot http://i.imgur.com/jKrhXiU.png

**Comment by RoelN** [comment] 2017-08-22 07:45
NotoColorEmoji.ttf can't be installed because Windows thinks it's a broken font. The CBDT specsays there shouldn't be regular outlines present in the font. Windows assumes these missing outlines indicate a broken font, so it won't let it be installed.

To fix this, Windows should update it's is-this-font-valid process to allow outline-less fonts when a CBDT table is present, or the CBDT/CBLC spec should be changed to allow for outlines (which would be the sanest solution).

**Comment by twardoch** [comment] 2017-08-22 15:07
@RoelN Could you point us to where exactly “the CBDT spec says there shouldn't be regular outlines present in the font”? 

1. The [OpenType font file](https://www.microsoft.com/typography/otspec/otff.htm#bitmapTables) portion of the OpenType spec says <q>OpenType fonts may also contain bitmaps of glyphs, in addition to outlines. Hand-tuned bitmaps are especially useful in OpenType fonts for representing complex glyphs at very small sizes. If a bitmap for a particular size is provided in a font, it will be used by the system instead of the outline when rendering the glyph.</q>

2. The OpenType [CBDT table spec](https://www.microsoft.com/typography/otspec/cbdt.htm) says nothing about outlines. 

3. The [spec changelog](https://www.microsoft.com/typography/otspec/changes.htm) or the [recommendation section of the spec](https://www.microsoft.com/typography/otspec/recom.htm) say nothing about this.

**Comment by RoelN** [comment] 2017-08-22 19:35
@twardoch It has always been part of the proposal (see [your post](https://blog.fontlab.com/font-tech/color-fonts/color-font-format-proposals/)) but hadn't noticed this requirement has since disappeared. Which is great news! I presume the font was built according to the specs available before that happened.

**Comment by smarts** [comment] 2017-10-06 00:52
Any update on this? Us Windows users want no tofu too!

**Comment by behdad** [comment] 2017-10-07 10:14
> Any update on this? Us Windows users want no tofu too!

@twardoch to confirm.

The status is, Windows 10 update from Summer 2016 supports CBDT/CBLC.  So the question is, has someone tested Noto Color Emoji there and it doesn't work?  In that case, it might be https://github.com/googlei18n/noto-emoji/issues/43 then.  We should fix that one.

**Comment by behdad** [comment] 2017-10-12 08:40
Thanks @patrickdark.  We need someone to dump the font using ttx, change the CBLC / CBDT version number from 2 to 3, compile it back, and test.

**Comment by RoelN** [comment] 2017-10-12 09:15
Just changing the version number doesn't make the font work. Adding a `glyf` table with empty glyphs doesn't help either. I'm on Windows 10 Creators Update (version 1703, build 15058.0).

**Comment by KrasnayaPloshchad** [comment] 2017-10-12 15:52
@RoelN So what happened if adding zero width glyphs into `glyf` table ?

**Comment by RoelN** [comment] 2017-10-12 19:12
The same "The file 'C:\Users\Roel\Downloads\N.ttt' does not appear to be a valid font" error.

**Comment by trollworkout** [comment] 2017-10-14 09:34
IF you github search noto emoji color windows you will find one project that converted noto to SVG and can install it by replacing the Segoe UI Symbol and Segoe UI Emoji but the issue is Windows changed how emojis work in 8.1 and it only shows black and white. But is proof that it can work is just too much trouble to get this working

**Comment by amckinlay** [comment] 2018-01-02 09:13
So this is a Microsoft bug @twardoch?

**Comment by twardoch** [comment] 2018-01-03 11:06
I don't have up-to-date Windows at this point, sorry!

**Comment by KrasnayaPloshchad** [comment] 2018-01-03 13:11
>I don't have up-to-date Windows at this point, sorry!

https://www.microsoft.com/en-us/software-download/windows10ISO

**Comment by ismail** [comment] 2018-01-03 16:17
In case someone needs, here are ready to use Windows 10 VM images for 6 month testing: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by SUPERCILEX** [comment] 2018-04-25 02:49
I have the Anniversary update and still no luck.

**Comment by scriby** [comment] 2018-06-11 17:35
I did some testing today and the font is rendering properly in Chrome on Windows (back to 7.1), Mac, and Linux. I think the updates for this were included in Chrome v66.

**Comment by SUPERCILEX** [comment] 2018-06-11 19:33
@scriby Care to share how you managed to install the font on Windows? Or just in Chrome somehow?

**Comment by scriby** [comment] 2018-06-11 20:09
@SUPERCILEX Ah, sorry, I was just testing the font in Chrome, so please disregard.

**Comment by vpontin** [comment] 2018-06-22 08:43
Sorry, but isnt [this](https://github.com/DeeDeeG/noto-color-emoji-font#install-on-windows) an working conversion? Just installed on my Win10 computer and it shows correctly on Options app (thought it wont replace Segoe UI emoji without some work).

**Comment by smarts** [comment] 2018-06-22 16:08
@vpontin that appears to be a totally different font. you can see by looking at
[this](https://noto-website-2.storage.googleapis.com/samples/emoji-zsye-color_und-Zsye_norm_400_normal.png)
vs.
[this](https://raw.githubusercontent.com/DeeDeeG/noto-color-emoji-font/nougat-rebase/images/notocoloremoji-font-demo.png)
notice how the latter has the blob style emojis while the former has circular emojis

**Comment by DeeDeeG** [comment] 2018-06-22 19:08
Well, I made that repo that @vpontin mentioned, so I can comment on that...

[This repo that we're commenting in](https://github.com/googlei18n/noto-emoji/) is focused on building a PNG-based font. This repo's font works better in some places (especially recent GNOME-based Linux distros). This repo's font, if I recall, generally works well with Chrome. I think it also works with Firefox. Maybe Edge as well. But Windows won't install this repo's font, last I checked, so it's not very useful unless you can somehow get around that. (Hence [this whole issue we're commenting on right now](https://github.com/googlei18n/noto-emoji/issues/43).)

My repo is based on the SVGs only. My repo's font is easier to deal with on Windows, for now, since Windows will install it no problem. But I don't think the font from my repo works with Chrome. And it probably only works okay with Edge (I think some of the emoji get distorted and end up looking weird.) My repo's font does work fine with Firefox. :+1:

(Colorful fonts like these aren't supported consistently across platforms and across browsers right now.)

(And I have no idea what works with Safari... But this is about Windows anyway so that's off-topic a bit.)

Regarding my repo using the Oreo designs vs Nougat, Lollipop, etc... My repo aims to support all the designs. I have Lollipop and Nougat releases, and a mashup of Nougat with Lollipop. I'm still working on the Oreo designs, because they didn't export perfectly from their native editing program (Adobe Illustrator?) out to SVG format, so there's a lot of clean up work to make them look right. It's fairly tedious and not very exciting, but the font would look messed up without it. So Oreo isn't done yet at my repo. (I usually finish a release about a year after it's released at this repo, but there's no promises whatsoever. I'm just doing this as a volunteer in spare time.)

**Comment by be5invis** [comment] 2019-10-13 04:38
The test results from @fdwr's tool
![image](https://user-images.githubusercontent.com/240091/66710995-17842b00-ed38-11e9-8acb-c2ca8211e0f2.png)
So, DWrite support loading it but not GDI.

Some points  I found:
- No `glyf`.
- `cmap` only having a 3/10 subtable, without 3/1 subtable, which is something GDI dislikes.

**Comment by SnippitCoder** [comment] 2020-10-16 02:02
Hi, i saw this in 2020 is there any hope of getting support for noto emojis format? Im back to the "Not supported" error

**Comment by davelab6** [comment] 2020-10-20 00:59
> The test results from @fdwr's tool
> ![image](https://user-images.githubusercontent.com/240091/66710995-17842b00-ed38-11e9-8acb-c2ca8211e0f2.png)
> So, DWrite support loading it but not GDI.
> 
> Some points I found:
> 
> * No `glyf`.

As there's no black and white design for Noto Emoji, I think this won't be possible to fix technically; it would require design work.

> * `cmap` only having a 3/10 subtable, without 3/1 subtable, which is something GDI dislikes.

That seems like something we can fix technically. @RoelN does that description give you enough to go on to fix it?

**Comment by DeeDeeG** [comment] 2020-10-20 01:49
You could use the old black and white font, if it's acceptable that it's missing everything from the past several years.

https://github.com/googlefonts/noto-emoji/blob/master/fonts/NotoEmoji-Regular.ttf

That would mean there would be a `glyf` table, so maybe that would make it installable on Windows? (I vaguely recall there isn't supposed to be a `glyf` table in CBDT/CBLC fonts such as Noto Color Emoji? And even more-vaguely, I think it's not a problem if there _is_ a `glyf` table anyhow... but don't quote me on that.)

Not sure if this is a _good_ idea, just posting it as _an idea_.

**Comment by RoelN** [comment] 2020-10-20 13:35
We can add the `glyf` table and a `cmap` that makes Windows happy, sure.

 Downside of that approach is that the font will fail silently (in the eyes of the user) in a situation where CBDT/CBLC isn't supported, as it will show blank `glyf` glyphs.

**Comment by RoelN** [comment] 2020-10-27 15:03
Adding a `glyf` table with empty glyphs, a `loca` table, and a `cmap` CMAP4 3/1 table will make the font installable and work in Windows 10 (Home edition, version 20H2). At least, for as far as I could test: Paint 3D will use Noto Color Emoji for its emoji, but WordPad and Notepad will not apply Noto Color Emoji.

All this adds ~10KB to the font, which sounds reasonable on a ~10MB file. The manually built font can be found [here](http://pixelambacht.nl/dump/NotoColorEmoji-w10patch.ttf), if any Windows users want to test it out in other software. 

Regarding testing in TextLayoutSampler, only "D2D DrawTextLayout" always renders the color glyphs properly. I tried various combinations of `glyf` and `cmap`, but they would either not render er even error out with "Error drawing object 0x80004005".

If this version meets the requirement "works in Windows", I can submit a PR where the build process adds `glyf`, `loca` and `cmap`.

(Note that the current Noto Color Emoji version works in all versions of Edge. This test was specifically for Noto Color Emoji as installed "system font".)

**Comment by 13rac1** [comment] 2020-10-27 17:58
FWIW This issue is why I went through the hassle of creating a method to generate B&W glyphs for `twemoji-color-font` https://github.com/eosrei/twemoji-color-font/blob/585d2fe5/Makefile#L115-L128 They aren't perfect, but it's a good enough solution and better than empty.

**Comment by fdwr** [comment] 2020-10-28 01:32
> Regarding testing in TextLayoutSampler, only "D2D DrawTextLayout" always renders the color glyphs properly. I tried various combinations of `glyf` and `cmap`, but they would either not render er even error out with "Error drawing object 0x80004005".

@RoelN : Yeah, that is expected, as...
- GDI and GDI+ only support vector `glyf` outlines, not `COLR`, `CBDT`, or `SVG ` tables. I don't know what GDI+ is complaining about though :/ (returning a failing `Status::GenericError` from `Gdiplus::Graphics::DrawString`).
- DWrite itself reads the color table information (which D2D can query), but DWrite's own simple builtin `IDWriteBitmapRenderTarget::DrawGlyphRun` only supports vector graphics (glyf), and so to draw PNG glyphs, I'd have to check in TextLayoutSampler for `DWRITE_GLYPH_IMAGE_FORMATS_PNG` to then call WIC and GDI `StretchBlt` ([todo](https://github.com/fdwr/TextLayoutSampler/blob/5e678bb09316f9f46b9da52ce2675fb08ed85471/DWritEx.ixx#L2255)).
- Direct2D's `DrawTextLayout` and `DrawColorBitmapGlyphRun` directly support all the glyph image formats (PNG, TIFF, SVG...), making it trivial to implement. D2D is used by Edge, recent Office applications, and any WinUI XAML-based application. So that reaches a sizeable audience.

**Comment by RoelN** [comment] 2020-11-02 14:37
@fdwr I have a PR with a [proper build](https://github.com/googlefonts/noto-emoji/blob/a6543c344aff46ffdded6ae887448cae90fc06eb/fonts/NotoColorEmoji_WindowsCompatible.ttf), if you want to test with that!

**Closed** 2020-12-08 09:22 UTC
Labels: bug

**Comment by joshua-612** [comment] 2021-02-17 06:35
> @fdwr I have a PR with a [proper build](https://github.com/googlefonts/noto-emoji/blob/a6543c344aff46ffdded6ae887448cae90fc06eb/fonts/NotoColorEmoji_WindowsCompatible.ttf), if you want to test with that!



Could you please tell me how to set the windows compatible emojis as system default?

**Comment by RoelN** [comment] 2021-02-17 08:04
@joshua-612 I don't know, but perhaps you can find instructions elsewhere, e.g. https://superuser.com/questions/1062418/how-do-i-replace-windows-10s-emoji?

**Comment by fdwr** [comment] 2021-02-17 08:44
@RoelN : Cool (sorry for very late response - a sea of notifications 😅). Yep, testing your font, I'm able to *install* it fine. The emoji are fully rendered via D2D, blanks for DirectWrite (because I don't read PNG glyphs in TextLayoutSampler), emptiness for GDI (alas, it is highly unlikely GDI will ever read PNG glyphs), and an error for GDI+ (don't know what GDI+'s deal is). I wish there was a way to appease the installer so you can install the font, while still getting font fallback to Segoe UI Emoji for the unsupported PNG glyphs, but I don't think there is a way to satisfy both requirements.

![image](https://user-images.githubusercontent.com/1809166/108176820-4db58580-70b7-11eb-9be0-e35bb4c867b9.png)

**Comment by sparx058** [comment] 2021-02-20 08:18
> > @fdwr I have a PR with a [proper build](https://github.com/googlefonts/noto-emoji/blob/a6543c344aff46ffdded6ae887448cae90fc06eb/fonts/NotoColorEmoji_WindowsCompatible.ttf), if you want to test with that!
> 
> Could you please tell me how to set the windows compatible emojis as system default?

I tried that build but it changes nothing. The best you can have is to change font to _NotoEmoji._
While its still monochrome, it at least adds more emojis to what were previously rendered as "☐"

**Comment by macabeus** [comment] 2021-02-22 00:15
@RoelN I would like to use this font as default on Windows, so I needed to change the font name to `Segoe UI Emoji`. I tried to do that using Font Forge, but no file was output for some unknown reason.
Would it be possible to do that using another approach?

**Comment by RoelN** [comment] 2021-02-22 16:01
@fdwr Thanks for checking! I think perhaps checking for CBDT support, and then loading the appropriate font through CSS would be quicker than to hope/wait for a all-in-one solution :-)

@macabeus You could dump the font to a .ttx file, change the name, and compile it back to a .ttf using [ttx](https://github.com/fonttools/fonttools)?

**Comment by Funmoring46** [comment] 2021-08-02 22:54
I think it might work if we use this: https://github.com/eosrei/twemoji-color-font#replace-the-default-windows-emoji-fonts

And edit: `install.cmd`

**Comment by assiless** [comment] 2021-12-29 18:43
@fdwr's tool
> > So, DWrite support loading it but not GDI.
> > Some points I found:
> > 
> > * No `glyf`.
> 
> As there's no black and white design for Noto Emoji, I think this won't be possible to fix technically; it would require design work.
> That seems like something we can fix technically. @RoelN does that description give you enough to go on to fix it?
> Downside of that approach is that the font will fail silently (in the eyes of the user) in a situation where CBDT/CBLC isn't supported, as it will show blank `glyf` glyphs.
> Paint 3D will use Noto Color Emoji for its emoji, but WordPad and Notepad will not apply Noto Color Emoji.

@fdwr @RoelN 
is now possible to make cbdt font with b&w for windows
https://github.com/adobe-fonts/noto-emoji-svg

**Comment by SaveTheRbtz** [comment] 2022-04-03 22:22
Should we make `cmap4` and `glyf` generation a default?  Size increase is negligible (8KiB on a 10MiB file) but it will simplify font installation.
(cc: @RoelN)
