### ISSUE TITLE
Readme incorrectly states that NotoColorEmoji works on Windows

### ISSUE THREAD

**Issue by smarts** [googlefonts/noto-emoji#289] opened 2020-02-12 18:50 UTC
I have Windows 10 version 1903 (which is more recent than the version that is supposed to support NotoColorEmoji, version 1607) and the NotoColorEmoji font still doesn't work.
`The file '…\NotoColorEmoji.ttf' does not appear to be a valid font.`
This has been an issue for years now and hasn't been fixed. Is this project/repository even active still?

**Comment by GiancarlosIO** [comment] 2020-08-23 22:53
Yep, same here :(

**Comment by zac1st1k** [comment] 2020-10-13 14:29
same

**Comment by tomasdev** [comment] 2020-10-27 10:33
Duplicate of #43

**Closed by tomasdev** 2020-10-27 10:33 UTC

**Comment by smarts** [comment] 2020-11-09 23:38
@tomasdev this isn't a duplicate. THAT issue is about the font not working in Windows. THIS issue is about incorrect documentation.
