### ISSUE TITLE
Firefox, not all emoji showing

### ISSUE THREAD

**Issue by wokalek** [googlefonts/noto-emoji#427] opened 2023-07-04 09:26 UTC
Why this is happend? How to fix?

![image](https://github.com/googlefonts/noto-emoji/assets/23037847/56caa079-936c-499c-b48d-648f694ee630)

**Comment by anthrotype** [comment] 2023-07-04 09:35
duplicate of https://github.com/googlefonts/noto-emoji/issues/391

**Closed by anthrotype** 2023-07-04 09:35 UTC
